### ISSUE TITLE
Incorrect Company Name

### ISSUE THREAD

**Issue by ankitjaggi** [deepakpathania/deepakpathania.github.io#2]
Deepak Pathania no longer works at Postman. You are trying to defame the company by still associating himself with the company. Kindly update your company name, or be ready for a multi-million dollar lawsuit against you!

**Comment by deepakpathania** [comment]
What are you talking about? I sit right next to you in the office. Just because I am on leave doesn't mean I have left. Closing due to fallacy in the stated information.

**Comment by elssar** [comment]
Erm, your own Gihub profile states that you are **Ex** Product Engineer @ Postman :roll_eyes:
![pathania-github-profile](https://user-images.githubusercontent.com/1042301/61774754-2df3a800-ae15-11e9-93e5-a1168a929ab5.png)

**Comment by deepakpathania** [comment]
Ex: here stands for Extraordinary. What is your point?
